web/src/components/Header/index.tsx
change header docs link from https://github.com/nervosnetwork/docs
to https://docs.nervos.org/
=> chore: change header docs link

server/app/controllers/api/v1/blocks_controller.rb, server/test/controllers/api/v1/blocks_controller_test.rb
avoid calculated totals blocks (call `count(*)`) frequently on home page
=> [ᚬrelease] chore(server): speed up blocks api

app/workers/PoolTransactionCheckWorker.rb
A transaction with dead cell-deps should be treated as a double-spending transaction.
Due to my lack of familiarity with Ruby, I have not tested this change.
=> fix: filter out pending transactions with dead cell-deps

app/models/cell_output.rb, app/models/ckb_sync/new_node_data_processor.rb, app/models/ckb_transaction.rb, app/models/nrc_factory_cell.rb, app/models/udt.rb, app/serializers/address_serializer.rb, db/migrate/20220311140723_create_nrc_factory_cell.rb, db/migrate/20220311144809_add_nrc_factory_cell_id_to_udts.rb, db/schema.rb, lib/tasks/migration/fill_nrc_721_token.rake
1. 新增一个 nrc_factory_cell 的表用于储存链上的factory cell
2. 当开发者提供factory cell 的时候，我们就运行` rake migration:update_nrc_721_token_info[factory_code_hash, factory_hash_type, factory_args]` 解析这个 factory cell 并标记verified
3. udt 会和 nrc_factory_cell  有个关联，每次都会检查这个factory cell 是否验证过，验证过就将识别出来的信息同步到 udt 表里
=> Feat 873 5

app/models/ckb_sync/new_node_data_processor.rb
The UDT build codes may give `udt_attributes` different fields conditionally.
And rails cannot use `insert_all` for attributes with different keys in items.
So create UDT record one by one.
=> Fix udt insertion

app/models/cell_output.rb, app/models/ckb_transaction.rb, db/migrate/20220711181425_add_contained_address_ids_index_to_ckb_transactions.rb, db/migrate/20220711183054_remove_old_contained_address_ids_index_from_ckb_transactions.rb, db/schema.rb
Some addresses contains too many transactions ( > 100000), cause pagination very slow.
I create a new union index to cover filtering and ordering to optimize that performance.
=> create index for ckb transaction to optimize performance

app/controllers/api/v1/distribution_data_controller.rb, app/models/average_block_time_by_hour.rb, app/models/daily_statistic.rb, app/models/rolling_avg_block_time.rb, app/services/charts/daily_statistic_generator.rb, app/workers/average_block_time_generator.rb, config/schedule.yml, db/migrate/20220705003300_create_average_block_time_by_hour_view.rb, db/schema.rb, test/services/charts/daily_statistic_generator_test.rb
The previous way to generate rolling average block time statistics is manually aggregate data from database using rails code.
Now I take advantage of Materialized View to generate statistics from the database level, so that the source codes can be simplified.
And the ancient data can be rebuilt directly.
=> use materialized view to generate rolling average block time

app/controllers/api/v1/address_transactions_controller.rb, app/models/account_book.rb, app/models/ckb_transaction.rb, db/migrate/20220716080815_create_ckb_transaction_account_book_trigger.rb, db/schema.rb
Some address contains too many transactions. And the current indexes cannot cover this scenario.
`contained_address_ids` column in `ckb_transactions` table is an array type column, and the index on this column cannot combine with other simple column to both cover sorting and filtering.
So I reuse previous deprecated `account_books` intermediate table, which setup association between `ckb_transactions` and  `addresses`. And make composite indexes in this table to cover both address filtering and ckb transaction sorting .
However, in order to make minimum modifitication and not to introduce new bugs, I use table trigger in Postgresql to synchonize between `ckb_transactions.contained_address_ids` column and `account_books` table. So I can keep current block synchronization process untouched …
=> Use AccountBook intermediate table to optimize transaction query on specific address.

app/models/address.rb, config/environments/test.rb, db/structure.sql
Some address may not have corresponding lock script record
Then the serialization for the address record will fail to extract lock script info, causing 404 error.
This patch will return lock script parsed from address hash.
=> Fix address API returns 404

app/controllers/api/v1/ckb_transactions_controller.rb, config/routes.rb, test/controllers/api/v1/ckb_transactions_controller_test.rb, test/test_helper.rb
Some address may make url exceed the maximum length supported by browser, cause browser truncate request url or fetch failed.
So I added an POST API for client, so that we can put address params in post body.
=> Support query transaction against too long address

app/controllers/api/v1/ckb_transactions_controller.rb, app/models/pool_transaction_entry.rb, test/models/pool_transaction_entry_test.rb
update strategy: when user visit a "rejected" transaction which has `no detailed_message`, the backend will update its detailed_message.
So there is no need to run a specific method in `rails console`.
please review
=> fixed #101: Sync rejected messages of historical transactions

app/workers/fetch_cota_worker.rb
The API doc of cota aggregator said the field name is `type`, but the actual response return by server is `tx_type`
Ref: https://github.com/nervina-labs/cota-aggregator/issues/138
=> Fix field name returned by cota aggregator

app/models/token_item.rb, app/workers/token_transfer_detect_worker.rb, db/structure.sql
currently, there is an error when deploying to staging server:
```
You tried to define an enum named "status" on the model "TokenItem", but this will generate a instance method "destroyed?", which is already defined by Active Record
```
the root cause is: in ActiveRecord, programmer should not define enum named `destroyed`, which is already an existing method.
so solution is rename: `destroyed` -> `is_destroyed` in model's enum.
=> fixed error: in app/models/token_item.rb,enum status

app/controllers/api/v2/pending_transactions_controller.rb
corrected the page count for api: pending transaction list. 
related issue:  https://github.com/Magickbase/ckb-explorer-public-issues/issues/178
=> fixed bug: should show correct pagination count

app/models/ckb_sync/new_node_data_processor.rb
related issue : https://github.com/Magickbase/ckb-explorer-public-issues/issues/188
=> fix error in block syncer: some cell does not always have lock/type script 

app/controllers/api/v2/statistics_controller.rb
improved the code , based on #1193 
1. only select pending tx which bytes is not 0, which transaction_fee > 0
2. rescue the exception when tx is dropped and not found .
=> create a patch for pending transactions fee rate api, 03-16

app/controllers/api/v2/statistics_controller.rb, app/models/ckb_transaction.rb, test/controllers/api/v2/statistics_controller_test.rb, test/factories/block.rb
The original algorithm is to fetch all ckb transactions from database and calculate day by bay in Rails layer.
I move the aggregation into database layer.
=> Optimize sql of last n days' fee rate

app/models/cell_output.rb, db/migrate/20230425114436_add_cell_type_index_to_cell_output.rb, db/structure.sql
Before cell_outputs table only have status index.So when we run `CellOutput.nervos_dao_deposit.live` code is very slow.
After add cell_type index, became faster.
- - -
Run this migration may need 2 minutes.
=> feat: add cell_type index to cell_outputs table

app/workers/charts/daily_statistic.rb
The daily statistic generator may build the data of current day, but current day may not end.
=> Fix the daily statistic data generation

Gemfile, Gemfile.lock, config/environments/development.rb, config/environments/production.rb
Add a namespace for caches, in order to clear only rails cache, not affecting sidekiq queues
use hiredis driver for better performance
=> Add namespace for Rails cache

app/models/address.rb, app/models/ckb_sync/node_data_processor.rb, app/models/ckb_transaction.rb, app/views/api/v2/scripts/ckb_transactions.json.jbuilder
`dao_address_ids` & `udt_address_ids` are removed from`ckb_transactions` table
change to correct name
=> Upgrade legacy fields to correct name

app/models/udt.rb
The direct call for `present?` on ActiveRecord relation will fetch all records and then check, so caused memory bloat.
Use `exists?` to check on database.
=> fix memory leak in udt transaction count

config/initializers/config_check.rb, lib/ckb_block_node_processor.rb, lib/websocket.rb
https://github.com/Magickbase/ckb-explorer-public-issues/issues/329
=> only check ckb node in blocksyncer, poolsyncer

lib/websocket.rb
The import transaction is synchronous, and when a database error is reported, the thread will exit.
=> chore: catch import transaction error

app/controllers/api/v1/udts_controller.rb, app/lib/api/v1/exceptions.rb, app/models/udt.rb, config/routes.rb, db/migrate/20230808020637_add_contact_info_to_udts.rb, db/structure.sql, test/controllers/api/v1/udts_controller_test.rb, test/test_helper.rb
https://github.com/Magickbase/ckb-explorer-public-issues/issues/374
=> feat: update udt info through api

app/jobs/import_transaction_job.rb, lib/websocket.rb
https://github.com/nervosnetwork/ckb-explorer/blob/develop/app/models/cell_output.rb#L84
has already create cell datum.
Cell does not reload, so repeated creation will cause errors: 
```bash
error: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "cell_data_pkey"
DETAIL:  Key (cell_output_id)=(1263805) already exists.
```
=> fix: remove duplicate cell datum when importing pending transactions

app/controllers/api/v1/address_transactions_controller.rb, app/controllers/api/v1/blocks_controller.rb, app/controllers/api/v1/udts_controller.rb, app/jobs/csv_exportable/base_exporter.rb, app/jobs/csv_exportable/export_address_transactions_job.rb, app/jobs/csv_exportable/export_block_transactions_job.rb, app/jobs/csv_exportable/export_nft_transactions_job.rb, app/jobs/csv_exportable/export_udt_transactions_job.rb, test/controllers/api/v1/address_transactions_controller_test.rb, test/controllers/api/v1/blocks_controller_test.rb, test/controllers/api/v1/udts_controller_test.rb, test/controllers/api/v2/nft/transfers_controller_test.rb
Because the page displays the local time, the database comparison is utc, so the time zone conversion is performed directly on the front end.
=> chore: adjust the date parameter to a timestamp

app/controllers/api/v1/contract_transactions_controller.rb, test/controllers/api/v1/contract_transactions_controller_test.rb
The `address_dao_transactions` table only stores cell data whose cell_type is `nervos_dao_deposit` and `nervos_dao_withdrawing`. So there is no way to filter other types of cells by address.
=> fix: filter dao transactions by address hash

app/workers/token_transfer_detect_worker.rb
The CleanUpWorker will auto remove creator_id were nil's records. So we need to save creator_id when create token collection.
=> Issue 395 8

app/models/ckb_sync/new_node_data_processor.rb, app/models/lock_script.rb, app/models/script.rb, app/models/type_script.rb
The same type script exist 4 records in our database.So find_by is not correct.
=> fix: current exist no binded type script that cause wrong query

app/controllers/api/v2/ckb_transactions_controller.rb
```ruby
{
"data": [
{
"address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0kx3w9a2jsvw8qgut0wpnadx9e96mdsscdu632j",
"transfers": [
{
"capacity": "0.0",
"cell_type": "m_nft_class",
"m_nft_info": {
"class_name": "背包女孩",
"total": "50"
}
}
]
},
{
"address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqwzkxjqa49qm6cye9jak2upf07nzmm05zqv5h6ux",
"transfers": [
{
"capacity": "-13400001178.0",
"cell_type": "normal"
}
]
},
{
"address": "ckt1qqfy5cxd0x0pl09xvsvkmert8alsajm38qfnmjh2fzfu2804kq47vq2uepjud49tqrwf3dm7ygcgw6rz2mqp89calzzec",
"transfers": [
{
"capacity": "13400000000.0",
"cell_type": "m_nft_token",
"m_nft_info": {
"class_name": "背包女孩",
"token_id": "00000000",
"total": "50"
}
}
]
}
]
}
```
=> feat: transaction detail info add m_nft_info

app/models/statistic_info.rb, app/serializers/statistic_serializer.rb, test/controllers/api/v1/statistics_controller_test.rb
```json
{
"data": {
"id": "1",
"type": "statistic",
"attributes": {
"blockchain_info": {
"is_initial_block_download": false,
"epoch": 1979125929614586,
"difficulty": 471576372,
"median_time": 1697087655463,
"chain": "ckb_testnet",
"alerts": []
}
}
}
}
```
=> fix: blockchain info statistic

app/models/deployed_cell.rb
https://explorer.nervos.org/transaction/0xab0877e51785419489f0a5049250c08e47dbdb2fee1a6c8a37ae10dd523090a7
```ruby
{"cycles"=>"0x6c32eb",
"time_added_to_pool"=>nil,
"transaction"=>
{"cell_deps"=>
[{"dep_type"=>"dep_group", "out_point"=>{"index"=>"0x0", "tx_hash"=>"0xf05188e5f3a6767fc4687faf45ba5f1a6e25d3ada6129dae8722cb282f262493"}},
{"dep_type"=>"code", "out_point"=>{"index"=>"0x2", "tx_hash"=>"0x5dce8acab1750d4790059f22284870216db086cb32ba118ee5e08b97dc21d471"}}],
"hash"=>"0xab0877e51785419489f0a5049250c08e47dbdb2fee1a6c8a37ae10dd523090a7",
"header_deps"=>[],
"inputs"=>[{"previous_output"=>{"index"=>"0x1", "tx_hash"=>"0xd24e1ae55741c46994f11627b63cb3aedd41b769accfcb1daa5ddf1461f098b8"}, "since"=>"0x0"}],
"outputs"=>
[{"capacity"=>"0x32a9f80c6", …
```
=> fix: query cell_output by hex index

app/utils/ckb_utils.rb, test/models/ckb_sync/node_data_processor_test.rb, test/utils/ckb_utils_test.rb
https://github.com/Magickbase/ckb-explorer-public-issues/issues/487
=> feat: re-calculate epoch reward after halving

app/controllers/api/v1/address_transactions_controller.rb, app/lib/fast_jsonapi/pagination_meta_generator.rb
Query and cache are optimized, but the total_count still takes a long time, for example, when the total number of transactions for the address `ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqwhc5slwl9w88nss0gu6ej23yeetl39lkcs28h94` exceeds 4 million. Can we limit the total count query to, for example, 500,000?
@Keith-CY @zmcNotafraid
=> refactor: address transaction query

app/controllers/api/v2/scripts_controller.rb
https://github.com/Magickbase/ckb-explorer-frontend/pull/118#issuecomment-1849191673
=> fix: scripts query empty result lead deadlock

app/serializers/ckb_transactions_serializer.rb, test/controllers/api/v1/suggest_queries_controller_test.rb
Because the redis configuration of node processor is different from the configuration of explorer api, only the cache key can be adjusted here.
=> fix: optimize transaction display cells cache key

app/models/ckb_sync/new_node_data_processor.rb
Using the `code_hash` of `lock_script` and the `script_hash` of `type_script` as the `code_hash` for the contract.
=> fix: fixed contract synchronization

app/utils/ckb_utils.rb, test/utils/ckb_utils_test.rb
udt's name and symbol have length limit. Must greater than or equal 1.But can be nil.
=> feat: omiga inscription name and symbol can't be null string

app/controllers/api/v1/omiga_inscriptions_controller.rb, app/jobs/csv_exportable/export_omiga_inscription_transactions_job.rb, app/models/ckb_sync/new_node_data_processor.rb, app/models/omiga_inscription_info.rb, app/serializers/udt_serializer.rb, db/migrate/20240119131328_add_pre_udt_hash_to_omiga_inscription_info.rb, db/structure.sql, test/controllers/api/v1/omiga_inscriptions_controller_test.rb, test/factories/omiga_inscription_info.rb, test/models/ckb_sync/node_data_processor_test.rb, vcr_fixtures/vcr_cassettes/blocks/33.yml
When inscription start rebase, we bind new inscription with old inscription through pre_udt_hash.In index page, we need to filter old inscription, keep new inscription.
=> Issue 508 14

app/controllers/api/v2/scripts_controller.rb, config/routes/v2.rb, test/controllers/api/v2/scripts_controller_test.rb, test/factories/contract.rb
https://ckb-explorer.readme.io/reference/contract-referring-capacities
=> feat: add contract referring capacities

config/initializers/sentry.rb
There were too many sentry transaction logs sent.And we only use new relic to watch performance.
=> chore: remove sentry transaction performance tracer

app/controllers/api/v1/address_udt_transactions_controller.rb, app/controllers/api/v1/udt_transactions_controller.rb, app/models/ckb_sync/new_node_data_processor.rb, app/models/omiga_inscription_info.rb, app/serializers/udt_serializer.rb, db/migrate/20240313075641_add_is_repeated_symbol_to_omiga_inscription_info.rb, db/structure.sql, test/controllers/api/v1/address_udt_transactions_controller_test.rb, test/controllers/api/v1/omiga_inscriptions_controller_test.rb, test/models/ckb_sync/node_data_processor_test.rb
Before we use udt's  published attribute to mark a omiga inscription is repeated symbol or not. But the published value was used in other code and confused us. So we add a new attribute in omiga inscription info table to check omiga inscription was repeated or not.
=> Issue 527 3

app/interactions/addresses/live_cells.rb
=> refactor: use block_timestamp index is very slow, query ids first then
