src/components/transaction.vue

- fixed transaction data not displayed issue 
Before
After

fix: fix transaction data not dispalyed issue

---

src/components/app.vue
src/components/block.vue
src/components/home.vue
src/components/transaction.vue

RPC result path has been changed.
This pr updates all the path for parsing RPC result.

fix rpc result incorrect

---

web/package.json
web/src/components/Label/CellConsumedLabel/index.tsx
web/src/components/Label/index.tsx
web/src/components/Table/index.tsx
web/src/pages/Address/index.css.tsx
web/src/pages/Address/index.tsx
web/src/pages/BlockDetail/index.css.tsx
web/src/pages/BlockDetail/index.tsx
web/src/pages/BlockList/index.css.tsx
web/src/pages/BlockList/index.tsx
web/src/pages/Home/index.css.tsx
web/src/pages/Home/index.tsx
web/src/pages/SearchFail/index.tsx

The components impact many pages, so there are many file changes in this pr.
But there are a lot places which need to be refactored, I just submit firstly to avoid too long code.

feat: Add table and label component

---

server/.rubocop.yml
server/app/controllers/api/v1/blocks_controller.rb
server/app/controllers/api/v1/ckb_transactions_controller.rb
server/app/controllers/application_controller.rb
server/app/controllers/validations/block.rb
server/app/controllers/validations/ckb_transaction.rb
server/app/controllers/validations/pagination.rb
server/app/models/block.rb
server/app/models/ckb_transaction.rb
server/app/serializers/request_error_serializer.rb
server/config/application.rb
server/lib/api/v1/exceptions.rb
server/lib/fast_jsonapi/error_serializer.rb
server/test/controllers/api/v1/blocks_controller_test.rb
server/test/controllers/api/v1/ckb_transactions_controller_test.rb

1. create block, transaction validation.
2. use those validation on before action.
3. adjust related tests.
4. use RequestErrorSerializer in api_error function.
5. remove useless comment on rubocop config file.

feat(server): use another way to do validation

---

server/Gemfile
server/Gemfile.lock
server/app/controllers/api/v1/address_transactions_controller.rb
server/app/controllers/validations/address_transaction.rb
server/app/models/ckb_transaction.rb
server/app/serializers/request_error_serializer.rb
server/config/routes.rb
server/lib/api/v1/exceptions.rb
server/test/controllers/api/v1/address_transactions_controller_test.rb
server/test/factories/account.rb
server/test/factories/ckb_transaction.rb

1. add address transactions show api.
2. add address transactions show api test.
3. add faker gem.
4. remove message attribute from RequestErrorSerializer.

feat(server): add address transactions api and tests

---

server/.rubocop.yml
server/Gemfile
server/Gemfile.lock
server/app/models/block.rb
server/test/controllers/api/v1/blocks_controller_test.rb
server/test/factories/block.rb

1. add pagination  params test.
2. adjust blocks controller tests ordering.
3. ignore tests folder and config environment folder on rubocop

chore(server): update blocks controller test

---

server/test/controllers/api/v1/address_transactions_controller_test.rb
server/test/controllers/api/v1/blocks_controller_test.rb

1. add no records found test when call index api. 
2. update only set page size test to add return value check.

chore(server): update paging related test

---

server/app/controllers/api/v1/address_transactions_controller.rb
server/app/controllers/api/v1/block_transactions_controller.rb
server/app/controllers/api/v1/blocks_controller.rb
server/lib/fast_jsonapi/pagination_meta_generator.rb
server/test/controllers/api/v1/address_transactions_controller_test.rb
server/test/controllers/api/v1/block_transactions_controller_test.rb
server/test/controllers/api/v1/blocks_controller_test.rb

1. add PaginationMetaGenerator.
2. add links to response object.
3. add meta to response object.
4. adjust related tests.

feat(server): add pagination options

---

server/app/controllers/validations/address.rb
server/app/controllers/validations/address_transaction.rb
server/app/controllers/validations/suggestquery.rb
server/app/models/address.rb
server/app/models/block.rb
server/app/models/suggest_query.rb
server/config/initializers/ckb/utils.rb
server/test/controllers/api/v1/address_transactions_controller_test.rb
server/test/controllers/api/v1/addresses_controller_test.rb
server/test/controllers/api/v1/suggest_queries_controller_test.rb
server/test/factories/address.rb

1. change address validation.
2. change find record way.
3. adjust tests.

chore(server): update address api

---

server/app/controllers/validations/address.rb
server/app/controllers/validations/address_transaction.rb
server/app/controllers/validations/suggestquery.rb
server/app/models/address.rb
server/app/models/ckb_sync/persist.rb
server/app/models/ckb_sync/validator.rb
server/app/models/suggest_query.rb
server/config/initializers/ckb/utils.rb
server/lib/utils/ckb_utils.rb
server/test/factories/lock_script.rb
server/test/models/address_test.rb
server/test/models/ckb_sync/persist_test.rb
server/test/models/type_script_test.rb
server/test/models/uncle_block_test.rb
server/test/test_helper.rb

1. check if the default lock script is used.
2. adjust tests.

chore(server): change generate address

---

web/src/components/Label/CellConsumedLabel/index.tsx
web/src/components/Transaction/styled.tsx

* Update cell consumed text color to black
* Update transaction hash text color to black

chore: ui bugfix

---

web/src/App.tsx
web/src/components/Footer/index.tsx
web/src/components/Header/index.tsx
web/src/components/Loading/index.tsx
web/src/components/Search/index.tsx
web/src/components/Transaction/styled.tsx
web/src/contexts/App.tsx
web/src/pages/BlockDetail/index.tsx
web/src/pages/BlockList/index.tsx
web/src/pages/Home/index.tsx
web/src/pages/Transaction/index.tsx
web/src/providers/index.tsx

* Update ckb rpc doc url
* Hide blockNext icon for latest block
* Add loading animation for pages
* Add `console.error` for http request

chore: fix blockNext action bugs and add loading animation

---

server/config/deploy.rb

1. touch settings.local.yml
2. add daemon reload command

chore(server): update deploy script

---

web/src/components/Search/index.tsx
web/src/pages/SearchFail/index.tsx

* Delete search keyword of input when search success
* Retain error search keyword of input when search failed

chore(ui): update search content logic

---

server/app/models/ckb_sync/persist.rb
server/app/utils/ckb_utils.rb
server/test/models/ckb_sync/persist_test.rb

get block reward from cellbase

[ᚬmaster] fix(server): wrong block reward

---

web/src/pages/Address/index.tsx
web/src/pages/Address/styled.tsx
web/src/pages/BlockDetail/index.tsx
web/src/pages/BlockDetail/styled.tsx
web/src/pages/BlockList/index.tsx
web/src/pages/BlockList/styled.tsx

* Adapt address and block list pagination for mobile
* Remove separate line of block detail common information

feat(ui): fix release ui bug

---

server/app/controllers/api/v1/blocks_controller.rb
server/test/controllers/api/v1/blocks_controller_test.rb

avoid calculated totals blocks (call count(*)) frequently on home page

chore(server):  chore(server): speed up blocks api

---

server/Gemfile
server/Gemfile.lock

Reverts nervosnetwork/ckb-explorer#222

Revert "[ᚬrelease] chore(server): use rc"

---

app/controllers/api/v1/blocks_controller.rb
app/models/block.rb
app/models/statistic_info.rb
app/serializers/index_statistic_serializer.rb
db/migrate/20190617015612_remove_indexes_from_blocks.rb
db/migrate/20190617015805_add_index_on_number_to_blocks.rb
db/schema.rb

- GET /api/v1/statistics
- GET /api/v1/blocks/:block_hash
- GET /api/v1/blocks/:height

perf: api part1

---

app/models/ckb_sync/node_data_processor.rb

perf: update address transactions count speed

---

app/controllers/api/v1/block_statistics_controller.rb
app/controllers/api/v1/epoch_statistics_controller.rb
app/controllers/validations/block_statistic.rb
app/controllers/validations/epoch_statistic.rb
app/models/block_statistic.rb
app/models/epoch_statistic.rb
app/serializers/block_statistic_serializer.rb
app/serializers/epoch_statistic_serializer.rb
app/workers/charts/block_statistic.rb
app/workers/charts/epoch_statistic.rb
config/routes.rb
config/schedule.yml
db/migrate/20191201023327_create_block_statistics.rb
db/migrate/20191201111810_create_epoch_statistics.rb
db/schema.rb
doc/api.raml
lib/tasks/migration/generate_block_statistic_data.rake
lib/tasks/migration/generate_epoch_statistic_data.rake
public/api_doc.html
test/controllers/api/v1/block_statistics_controller_test.rb
test/controllers/api/v1/epoch_statistics_controller_test.rb
test/factories/block_statistic.rb
test/factories/epoch_statistic.rb

need execute two task:
1. `RAILS_ENV=production bundle exec rake migration:generate_block_statistic_data`
2. `RAILS_ENV=production bundle exec rake migration:generate_epoch_statistic_data`

feat: add block and epoch statistic

---

app/models/block_statistic.rb
app/models/daily_statistic.rb
app/serializers/block_statistic_serializer.rb
app/serializers/daily_statistic_serializer.rb
app/workers/charts/block_statistic.rb
db/migrate/20191202080732_change_integer_to_string_on_daily_statistics.rb
db/migrate/20191202081157_rename_cell_count_to_cells_count_on_block_statistics.rb
db/schema.rb
lib/tasks/migration/generate_block_statistic_data.rake
test/controllers/api/v1/block_statistics_controller_test.rb
test/factories/block_statistic.rb

1. change `addresses_count`, `transactions_count` and `total_dao_deposit` type from integer to string.
2. rename `live_cell_count` and `dead_cell_count` to `live_cells_count` and `dead_cells_count`

refactor: adjust tables

---

app/controllers/api/v1/block_statistics_controller.rb
app/controllers/api/v1/epoch_statistics_controller.rb
app/models/block_statistic.rb
app/models/epoch_statistic.rb
app/serializers/block_statistic_serializer.rb
app/serializers/epoch_statistic_serializer.rb
app/workers/charts/block_statistic.rb
app/workers/charts/epoch_statistic.rb
db/migrate/20191208071607_change_epoch_number_to_decimal.rb
db/migrate/20191209054145_add_epoch_number_to_block_statistics.rb
db/schema.rb
lib/tasks/migration/generate_block_statistic_data.rake
test/controllers/api/v1/block_statistics_controller_test.rb
test/controllers/api/v1/epoch_statistics_controller_test.rb

1. change `block_number` column type to `Decimal` and add index on it.
2. change `epoch_number` column type to `Decimal` and add index on it.
3. returns ascending data.

refactor: change epoch and block statistic

---

app/models/epoch_statistic.rb
app/serializers/epoch_statistic_serializer.rb
app/workers/charts/epoch_statistic.rb
db/migrate/20191226084920_add_hash_rate_to_epoch_statistic.rb
db/schema.rb
lib/tasks/migration/fill_hash_rate_to_epoch_statistic.rake
test/controllers/api/v1/epoch_statistics_controller_test.rb

need execute one task:
`RAILS_ENV=production bundle exec rake migration:fill_hash_rate_to_epoch_static`

feat: add hash rate to epoch statistic

---

app/models/address.rb
app/models/cell_output.rb
app/models/ckb_transaction.rb
app/models/dao_event.rb
app/services/charts/daily_statistic_generator.rb
db/migrate/20200110123617_add_index_to_block_timestamp_on_dao_events.rb
db/schema.rb
test/services/charts/daily_statistic_generator_test.rb

1. add indexes on dao event.
2. use scope replace where statement.
3. calculate addresses count incrementally.

refactor: dailay statistic generator

---

app/models/ckb_sync/node_data_processor.rb
app/models/udt.rb
app/serializers/address_serializer.rb
app/serializers/udt_serializer.rb
db/migrate/20200618102442_add_issuer_address_to_udts.rb
db/schema.rb
lib/tasks/migration/fill_issuer_address_to_udts.rake
test/controllers/api/v1/udts_controller_test.rb
test/factories/lock_script.rb
test/factories/udt.rb
test/models/ckb_sync/node_data_processor_test.rb
test/models/udt_test.rb

need to execute one task:
`RAILS_ENV=production bundle exec rake migration:fill_issuer_address_to_udts`

feat: add more info to sudt

---

app/models/address.rb
app/models/cell_output.rb
app/models/ckb_sync/node_data_processor.rb
app/models/null_address.rb
app/serializers/address_serializer.rb
app/services/charts/daily_statistic_generator.rb
app/workers/address_unclaimed_compensation_generator.rb
app/workers/dao_contract_unclaimed_compensation_generator.rb
config/schedule.yml
db/migrate/20200702035301_add_unclaimed_compensation_to_address.rb
db/migrate/20200703043629_add_is_depositor_to_addresses.rb
db/schema.rb
lib/tasks/migration/update_is_depositor.rake
lib/tasks/migration/update_unclaimed_compensations_on_daily_statistics.rake
test/controllers/api/v1/addresses_controller_test.rb
test/models/address_test.rb
test/services/charts/daily_statistic_generator_test.rb

need to execute two tasks: 
`RAILS_ENV=production bundle exec rake migration:update_is_depositor`
`RAILS_ENV=production bundle exec rake migration:update_unclaimed_compensations_on_daily_statistics`

feat: update dao compensation on address

---

.gitattributes
Gemfile.lock

* upgrade ruby concurrency to v1.1.7
* upgrade spring to v2.1.0

chore(dep): upgrade gems

---

Gemfile
Gemfile.lock

fix security issue: https://github.com/nervosnetwork/ckb-explorer/security/dependabot/Gemfile.lock/nokogiri/open

chore: upgrade nokogiri to 1.11.0.rc4

---

app/controllers/api/v1/daily_statistics_controller.rb
app/models/daily_statistic.rb
test/controllers/api/v1/daily_statistics_controller_test.rb

merge chart period changes to aggron

feat: return the recent year stat data

---

app/models/ckb_sync/new_node_data_processor.rb
lib/tasks/migration/fill_m_nft_token_full_name_and_icon.rake
test/models/ckb_sync/node_data_processor_test.rb

feat: save udt full_name and icon_file for m_nft_token udt

---

app/models/ckb_sync/new_node_data_processor.rb
lib/tasks/migration/fill_nrc_721_token.rake

1. Fix cell output can't get type script without type_script_id
2. Fix task

fix: select type_scrit_id for cell_output get type_script

---

app/models/cell_output.rb
app/models/ckb_transaction.rb
test/factories/nrc_factory_cell.rb
test/models/ckb_transaction_test.rb

Signed-off-by: Miles Zhang <mingchang555@hotmail.com>

test: nrc_721_nft_info

---

app/models/ckb_sync/new_node_data_processor.rb
test/models/ckb_sync/node_data_processor_test.rb

https://github.com/nervosnet/ckb-explorer-public-issues/issues/7

feat: keep dao_deposit 0 when a address have no deposit dao

---

app/models/ckb_sync/new_node_data_processor.rb
app/models/udt.rb
app/serializers/address_serializer.rb
lib/tasks/migration/fill_nrc_721_token.rake
test/controllers/api/v1/addresses_controller_test.rb
test/factories/nrc_factory_cell.rb
test/models/ckb_sync/node_data_processor_test.rb

1. 开发者更新nrc factory cell 的时候更新nrc_factroy_cell  的字段
2. 不从udt_account 读数据，而从nrc_factory_cell 读数据

feat: update nrc factory data when cell data is changed

---

app/controllers/api/v1/daily_statistics_controller.rb
app/controllers/api/v1/distribution_data_controller.rb
app/models/daily_statistic.rb
test/controllers/api/v1/daily_statistics_controller_test.rb

This is an port to apply this feature in current environment

change avg_hash_rate and avg block time to show full records

---

app/controllers/api/v1/udts_controller.rb

add a secondary order for equal address_count

adjust UDT list order

---

app/serializers/address_serializer.rb
config/initializers/rack_attack.rb

* fix nrc 721 account bug
* fix throttle bug ( rack attack ip detection ), using cloudflare header

Fix two bugs

---

Gemfile
Gemfile.lock
README.md
app/models/address.rb
app/models/cell_output.rb
app/models/ckb_sync/new_node_data_processor.rb
app/models/ckb_transaction.rb
app/serializers/address_serializer.rb
test/factories/cell_output.rb
test/models/ckb_sync/node_data_processor_test.rb

Revert differential calculation to full aggregation from database when block invalidation.

Fix negative balance & negative live cells count for addresses

---

.github/workflows/request-to-deploy-mainnet.yml
.github/workflows/request-to-deploy-testnet.yml

This commit adds two github actions to request deployment of mainnet and testnet

ci: add actions to request deployments

---

.github/workflows/mainnet.yml
.github/workflows/ruby.yml
.github/workflows/staging.yml
.github/workflows/testnet.yml

Fix the deploy branch of mainnet

fix github actions

---

app/controllers/api/v2/nft/transfers_controller.rb

fix param name

---

app/models/nrc_factory_cell.rb
app/models/token_collection.rb
app/serializers/address_serializer.rb
app/workers/token_transfer_detect_worker.rb

1. nrc_721 -> nrc721
2. format code

Fix typo in standard field

---

app/models/ckb_sync/new_node_data_processor.rb
lib/ckb_block_node_processor.rb

fixed: https://github.com/Magickbase/ckb-explorer-public-issues/issues/69
Changed metric strategy for processing nodes.
1. removed sentry
2. added newrelic
please review, thanks!

Changed metric strategy for processing nodes. 

---

app/models/token_collection.rb
app/workers/clean_up_worker.rb
config/schedule.yml

Periodically check the validation of token collection and remove those invalid records

Remove corrupted collection records

---

.github/workflows/ruby.yml
.github/workflows/staging.yml
app/workers/clean_up_worker.rb

to speed up the unit test.
And trigger workflow on specific tags for staging deployment.
Fix a small typo bug.

Cache compiled secp256k1 in GitHub Action

---

Gemfile
Gemfile.lock
app/controllers/api/v2/das_accounts_controller.rb
app/controllers/concerns/redis_cachable.rb
app/services/das_indexer_service.rb
config/environments/development.rb
config/routes.rb
test/controllers/api/v2/das_accounts_controller_test.rb
test/test_helper.rb

For query das account alias for specified ckb addresses
API doc: https://www.apifox.cn/apidoc/project-962207/api-20545372

Das Account API

---

app/models/dao_event.rb
app/utils/ckb_utils.rb

fixed bug.  for: https://github.com/Magickbase/ckb-explorer-public-issues/issues/110

fixed bug: should return correct from addresses

---

Gemfile
Gemfile.lock
app/models/ckb_sync/new_node_data_processor.rb

fixed this issue: https://github.com/Magickbase/ckb-explorer-public-issues/issues/113
1. used a patched gem for `sidekiq-cron`
2. used a patched gem for `sidekiq-statistics`
3. optimized the code ( slow query ) snipped using Rails.cache

Fix bug for upgrading to rails7

---

app/controllers/api/v2/dao_events_controller.rb

added logger to controller: dao_events. 
want to trigger an deployment.

add logger to dao_events controller. to trigger an deploy to test-net

---

app/services/das_indexer_service.rb

ignore these addresses and return empty result

Das indexer will raise "account not exist" error for some addresses

---

app/controllers/api/v2/pending_transactions_controller.rb
config/routes/v2.rb
test/controllers/api/v2/pending_transactions_controller_test.rb

refer to issue: https://github.com/Magickbase/ckb-explorer-public-issues/issues/154 
and:  https://github.com/Magickbase/ckb-explorer-public-issues/issues/130  
official document:  https://www.apifox.cn/apidoc/project-962207/api-58444841
GET : http://47.113.186.173:3040/api/v2/pending_transactions

backend api: show pending transactions for tx list page

---

app/controllers/api/v2/pending_transactions_controller.rb

forgot to commit this code, I am sorry. 
refer to issue: https://github.com/Magickbase/ckb-explorer-public-issues/issues/154
and: https://github.com/Magickbase/ckb-explorer-public-issues/issues/130
official document: https://www.apifox.cn/apidoc/project-962207/api-58444841

Pending transaction list page: fixed bug: missing 3 field from json result

---

app/models/block.rb
test/controllers/api/v2/blocks_controller_test.rb
test/models/block_test.rb

fix issue: https://github.com/Magickbase/ckb-explorer-public-issues/issues/182

extract node version from ckb_tx first witness string

---

app/controllers/api/v2/scripts_controller.rb
app/models/block.rb
config/routes/v2.rb
test/controllers/api/v2/scripts_controller_test.rb

related issue:  https://github.com/Magickbase/ckb-explorer-public-issues/issues/72
1. added `general_info` api
2. improved `transactions` api
3. improved the code

add page for script/contract: improved the code, add general info

---

app/models/lock_script.rb
app/models/type_script.rb

related issue: https://github.com/Magickbase/ckb-explorer-public-issues/issues/193
fixed the performance issue when querying `lock_script.ckb_transactions`

fixed slow query for querying tx by script

---

app/controllers/api/v2/scripts_controller.rb
app/models/cell_dependency.rb
app/models/cell_output.rb
app/models/ckb_sync/new_node_data_processor.rb
app/models/ckb_transaction.rb
app/models/contract.rb
app/models/deployed_cell.rb
app/models/referring_cell.rb
app/models/script.rb
app/models/script_transaction.rb
db/migrate/20230216084358_create_referring_cells.rb
db/migrate/20230218154437_add_script_id_to_cell_dependencies.rb
db/migrate/20230220013604_create_script_transactions.rb
db/migrate/20230220060922_add_indexes_to_scripts_and_cell_dependenices_and_deployed_cells.rb
db/structure.sql
test/controllers/api/v2/scripts_controller_test.rb
test/factories/referring_cell.rb
test/factories/script_transaction.rb
test/models/cell_dependency_test.rb
test/models/cell_output_test.rb
test/models/ckb_transaction_test.rb
test/models/contract_test.rb
test/models/deployed_cell_test.rb
test/models/referring_cell_test.rb
test/models/script_test.rb
test/models/script_transaction_test.rb

related issue: 
https://github.com/Magickbase/ckb-explorer-public-issues/issues/199 
https://github.com/Magickbase/ckb-explorer-public-issues/issues/198
1.created new table deployed_cells, 
2.implemented : how to create deployed_cells,
3.implemented: relationship of :contract-ckb_transactions,
4.added unit tests

fix two bugs:contract/script page

---

app/models/ckb_sync/new_node_data_processor.rb
app/models/ckb_transaction.rb
app/models/statistic_info.rb
db/structure.sql

this branch based on nervos testnet branch.
merged master.  resolved conflicts.

Fix conflicts based on testnet merged master

---

app/controllers/api/v2/scripts_controller.rb
config/routes/v2.rb

resolved performance issue .  please refer to this closed PR: https://github.com/nervosnetwork/ckb-explorer/pull/1121

added field for: script name, script type

---

app/controllers/api/v2/statistics_controller.rb
app/models/ckb_transaction.rb
test/controllers/api/v2/statistics_controller_test.rb

re-implemented this API: `/api/v2/statistics/transaction_fees`
now this API return correct result

fixed bug: "last n days fee rate " is not correct

---

app/serializers/ckb_transactions_serializer.rb
test/controllers/api/v1/address_dao_transactions_controller_test.rb
test/controllers/api/v1/address_transactions_controller_test.rb
test/controllers/api/v1/address_udt_transactions_controller_test.rb
test/controllers/api/v1/block_transactions_controller_test.rb
test/controllers/api/v1/contract_transactions_controller_test.rb
test/controllers/api/v1/udt_transactions_controller_test.rb

related issue: https://github.com/Magickbase/ckb-explorer-public-issues/issues/214

add fields for API: /api/v1/address_transactions/[:address]

---

app/models/address.rb
app/models/block.rb
app/models/cell_dependency.rb
app/models/ckb_transaction.rb
app/models/global_statistic.rb
app/models/lock_script.rb
app/models/pool_transaction_entry.rb
app/models/token_collection.rb
app/models/type_script.rb
app/models/udt.rb
db/migrate/20230403154742_expand_transaction_int_columns.rb
db/structure.sql

Expand bytes/cycles column in ckb_transactions to 8-bytes integer

Expand bytes/cycles column to 8-bytes integer

---

README.md
app/controllers/api/v2/scripts_controller.rb
app/serializers/scripts_ckb_transactions_serializer.rb
test/controllers/api/v2/statistics_controller_test.rb
test/models/cell_dependency_test.rb

this is a rebased version for:  PR: https://github.com/nervosnetwork/ckb-explorer/pull/1202

2023 04 04 rebased 03 20 using serializer in scripts controller

---

app/models/ckb_sync/new_node_data_processor.rb

Add an offset option for block syncing.
We only sync to tip_block_number - offset to avoid reorg

Offset option

---

config/initializers/cors.rb

this is the same feature with PR: https://github.com/nervosnetwork/ckb-explorer/pull/1223, just merge to testnet branch directly.

added more sites to cors config file

---

Gemfile
Gemfile.lock
app/controllers/api/v1/blocks_controller.rb
app/controllers/api/v1/ckb_transactions_controller.rb
app/controllers/api/v1/contract_transactions_controller.rb
app/lib/fast_jsonapi/pagination_meta_generator.rb

related issue:  https://github.com/Magickbase/ckb-explorer-public-issues/issues/212

Request to the last page of block list hangs

---

app/models/cell_output.rb
db/migrate/20230425114436_add_cell_type_index_to_cell_output.rb
db/structure.sql

Special merge to master directly

feat: add cell_type index to cell_outputs table

---

lib/tasks/migration/fix_daily_statistic_total_dao_deposit.rake
test/tasks/migrations/fix_daily_statistic_total_dao_deposit_test.rb

Run task `RAILS_ENV=production bundle exec rake migration:fix_daily_statistic_total_dao_deposit`

Issue 296 master

---

app/controllers/api/v2/monitors/daily_statistics_controller.rb
config/routes/v2.rb
test/controllers/api/v2/monitors/daily_statistics_controller_test.rb

related issue: https://github.com/Magickbase/ckb-explorer-public-issues/issues/252
closed PR: https://github.com/nervosnetwork/ckb-explorer/pull/1222 (which is out dated and hard to merge)

add monitor for daily_statistics

---

app/models/cell_output.rb
lib/tasks/migration/fix_address_balance_occupied.rake
test/tasks/migrations/fix_address_balance_occupied_test.rb

Fix address balance_occupied value bug.

fix: address balance occupied refresh bug

---

app/controllers/api/v2/scripts_controller.rb

https://github.com/Magickbase/ckb-explorer-public-issues/issues/303

Show latest transactions first in script transactions page

---

app/models/address.rb
app/models/block.rb
app/models/cell_input.rb
app/models/ckb_sync/node_data_processor.rb
app/workers/flush_inputs_outputs_cache_worker.rb
lib/tasks/migration/fill_nrc_721_token.rake
lib/tasks/migration/register_udt.rake

because now we have cache namespace in Rails cache store.
So we cannot use $redis to remove cache directly.

Fix cache deletion

---

app/controllers/api/v1/ckb_transactions_controller.rb
app/controllers/api/v2/pending_transactions_controller.rb

only show committed transaction ,no pending transaction

add tx_committed filter for transaction list

---

app/controllers/api/v1/blocks_controller.rb
app/models/block.rb
lib/scheduler.rb

And add connection pool support for scheduler

Optimize block query performance

---

test/controllers/api/v1/address_transactions_controller_test.rb
test/controllers/api/v1/blocks_controller_test.rb
test/factories/block.rb
test/models/global_statistic_test.rb
test/models/statistic_info_test.rb

Relevant issues:
https://github.com/Magickbase/ckb-explorer-public-issues/issues/322

fix: generate block fatory timestamp

---

app/controllers/api/v1/ckb_transactions_controller.rb
app/models/ckb_sync/new_node_data_processor.rb
app/models/ckb_transaction.rb
app/workers/pool_transaction_check_worker.rb

https://github.com/Magickbase/ckb-explorer-public-issues/issues/348

Fix transaction is always shown as pending

---

app/controllers/api/v1/block_transactions_controller.rb
app/controllers/validations/block_transaction.rb
app/models/record_counters/block_transactions.rb
test/controllers/api/v1/block_transactions_controller_test.rb

https://github.com/Magickbase/ckb-explorer-public-issues/issues/357

feat: filter transactions by address hash

---

db/structure.sql

Fix develop branch conflict with testnet branch

refactor: fix conflict with testnet

---

app/workers/clean_up_worker.rb

Remove outdated pending & rejected transactions from database

Clean up outdated transactions

---

app/models/daily_statistic.rb
app/services/charts/daily_statistic_generator.rb
db/migrate/20230630112234_add_uniq_index_to_daily_statistic.rb
db/structure.sql
test/services/charts/daily_statistic_generator_test.rb
test/workers/charts/daily_statistic_test.rb

refactor daily statistic genearator.

refactor: daily statistic generator use attr logic concern

---

app/controllers/api/v1/udts_controller.rb
app/jobs/export_address_transactions_job.rb
app/jobs/export_udt_transactions_job.rb
test/controllers/api/v1/udts_controller_test.rb

https://github.com/Magickbase/ckb-explorer-public-issues/issues/41

feat: reduce udt transactions export as csv n+1 querys

---

.github/workflows/mainnet.yml

https://github.com/Magickbase/infra/issues/54

chore: update mainnet workload

---

app/workers/clean_address_block_snapshot_worker.rb
lib/scheduler.rb
test/workers/clean_address_block_snapshot_worker_test.rb

https://github.com/Magickbase/ckb-explorer-public-issues/issues/398

feat: schedule clean address_block_snapshot data

---

app/controllers/api/v2/ckb_transactions_controller.rb
config/routes/v2.rb
test/controllers/api/v2/ckb_transactions_controller_test.rb

https://vs0cjf.axshare.com/?id=3giphq&p=_189_how_to_support_customers_and_developers_opera&g=1
```ruby
/api/v2/ckb_transactions/:id/details  # :id should be transaction's tx_hash
```
* Request
```ruby
/api/v2/ckb_transactions/0xc34e6549ea2f60429a775d7cb920b9f4fe1709662e07a276d4c738a11e2c7c3a/details
```
* Response
```json
{
"data": [
{
"address": "ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgq6lzjramu4cu7wzparntxf2yn8907yh7mqqan8g6y",
"transfers": [
{
"capacity": "0.0",
"cell_type": "normal"
}
]
},
{
"address": "ckt1qrl2cyw7ulrxu48ysexpwus46r9md670h5h73cxjh3zmxsf4gt3d5qg2d5amjwfzgtqr2l72ulxw4k8c0dpga55qjzdlm749f9ffhpwl8zc422t2hvxmtlkk299l30k6xlgccjps9pe2sfhx5y3flvtlu56lu0emx5qqqqqqqqgs9ggu",
"transfers": [
{
"capacity": "-50000000000000.0",
"cell_type": "normal"
}
]
},
{ …
```

feat: transaction lite info

---

.github/workflows/build.yml

https://github.com/marketplace/actions/free-disk-space-ubuntu

chore: free github action runner

---

app/models/token_item.rb
app/workers/token_transfer_detect_worker.rb
test/controllers/api/v2/nft/items_controller_test.rb

1. save args as token id
2. API adjust

Issue 395 3

---

app/controllers/api/v2/nft/transfers_controller.rb
app/controllers/api/v2/pending_transactions_controller.rb
test/controllers/api/v2/pending_transactions_controller_test.rb

some pending transactions missing inputs, so filter out this part of the data

feat: filter pending transactions without missing inputs

---

app/controllers/api/v2/scripts_controller.rb
app/jobs/revert_block_job.rb
app/models/cell_output.rb
app/models/ckb_sync/new_node_data_processor.rb
app/models/referring_cell.rb
app/views/api/v2/scripts/referring_cells.json.jbuilder
config/routes/v2.rb
db/migrate/20230829061910_add_indexes_to_referring_cells.rb
db/structure.sql
lib/tasks/migration/generate_referring_cells.rake
test/controllers/api/v2/scripts_controller_test.rb

```ruby
RAILS_ENV=production bundle exec rake migration:generate_referring_cells
```

feat: sync referring cells

---

Gemfile
Gemfile.lock
app/workers/contract_statistic_worker.rb
config/initializers/sidekiq.rb
config/routes.rb

feat: filter contract's referring cells of live status

---

Gemfile.lock

https://github.com/sidekiq/sidekiq/pull/6035

chore: sidekiq 7.1.3 has bug

---

app/workers/pool_transaction_check_worker.rb

Pending transactions on the testnet are accumulating rapidly. The deletion speed of pending transactions by PoolTransactionCheckWorker is too slow, leading to an accumulation of transactions.

feat: optimize batch size in PoolTransactionCheckWorker

---

app/controllers/api/v1/address_pending_transactions_controller.rb
app/models/address.rb
config/routes.rb
lib/tasks/migration/fix_address_balance_occupied.rake
test/controllers/api/v1/address_pending_transactions_controller_test.rb
test/factories/address.rb

https://ckb-explorer.readme.io/reference/pending-transactions-of-an-address

feat: add address pending transactions

---

app/controllers/api/v1/ckb_transactions_controller.rb
app/controllers/api/v2/ckb_transactions_controller.rb
app/serializers/ckb_transaction_serializer.rb
config/initializers/rack_attack.rb
config/routes.rb
config/routes/v2.rb

GET /api/v2/ckb_transactions/:id/display_outputs?page=2&page_size=2
GET /api/v2/ckb_transactions/:id/display_inputs?page=2&page_size=2

refactor: move display_inputs and display_outputs to api/v2

---

app/controllers/api/v2/ckb_transactions_controller.rb
app/controllers/concerns/cell_data_comparator.rb

- normal nft transfers
https://pudge.explorer.nervos.org/transaction/0xf5a466d0fcdc637c21a3be9341120a3f0fbe3c01f878285378f108da3830faeb
```json
{
"data": [
{
"address": "ckt1qpth5hjexr3wehtzqpm97dzzucgemjv7sl05wnez7y72hqvuszeyyq25rmcdw50zg8ppxudd6k7f0229q2jn4sqlcdx0k",
"transfers": [
{
"capacity": "-2188.0",
"cell_type": "m_nft_token",
"token_id": "2",
"collection_name": "1test",
"count": "-2"
},
{
"capacity": "-2275.0",
"cell_type": "m_nft_token",
"token_id": "2",
"collection_name": "2test",
"count": "-2"
},
{
"capacity": "-2362.0",
"cell_type": "m_nft_token",
"token_id": "4",
"collection_name": "3test",
"count": "-2"
},
{
"capacity": "-2449.0",
"cell_type": "m_nft_token",
"token_id": "2",
"collection_name": "4test",
"count": "-2"
},
{
"capacity": "-2536.0",
"cell_type": "m_nft_token", …
```

refactor: transaction details

---

Gemfile
Gemfile.lock
app/controllers/api/v1/xudts_controller.rb
config/environments/production.rb

This reverts commit d1bda0cad29ef7abf6c2775609eb5ae479478c1a.

Revert "chore: remove rack-cache (#1802)"

---

app/workers/charts/daily_statistic.rb

Reverts nervosnetwork/ckb-explorer#2288

Revert "fix: daily_stattistic generator condition"

---

app/models/address.rb

Reverts nervosnetwork/ckb-explorer#2365

Revert "hotfix address validate"

---

Gemfile.lock

Reverts nervosnetwork/ckb-explorer#2465

Revert "chore(deps): bump nokogiri from 1.18.3 to 1.18.4"

---

README.md
config/database.yml
config/settings.mainnet.yml
config/settings.testnet.yml
lib/ckb_block_node_processor.rb
test/controllers/api/v1/udts_controller_test.rb
test/workers/charts/daily_statistic_test.rb

chore: fix some typos

---

config/storage.yml
test/utils/ckb_utils_test.rb

fix some minor issues in comments

chore: fix some minor issues in comments

---

app/models/block.rb
test/models/block_test.rb

* perf: improve last_7_days_ckb_node_version
* chore: remove out date unit test

perf: improve last_7_days_ckb_node_version (#2654)

---

app/models/ckb_transaction.rb
db/migrate/20250827065749_add_block_number_index_to_ckb_transactions.rb
db/structure.sql

This reverts commit d896c875be2587673181f5d74a55c5a049a0bd84.

Revert "add add block_number index to ckb_transactions (#2668)"

---

app/jobs/revert_block_job.rb
app/models/ckb_sync/new_node_data_processor.rb
lib/scheduler.rb
test/factories/dao_event.rb
test/jobs/revert_block_job_test.rb
test/models/ckb_sync/node_data_processor_test.rb

* feat: incremental update address data when revert block
* feat: stop AddressBlockSnapshot save
* use balance_occupied instead of occupied_capacity; use update!() method
---------

Remove address block snapshot (#2689)
